import Head from "next/head"
import Image from "next/image"
import { Inter } from "next/font/google"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ challenges }) {
  return (
    <>
      <Head>
        <title>React coding challenges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <article>
          {challenges.map((challenge) => {
            return <h3>{challenge.title}</h3>
          })}
        </article>
      </main>
    </>
  )
}

export async function getStaticSidePaths() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  const paths = data.map((challenge) => {
    return {
      params: { title: challenge.title },
    }
  })
  return {
    paths,
    fallback: true,
  }
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  return {
    props: {
      challenges: data,
    },
  }
}
