import Head from "next/head"
// import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "../styles/HomePage.module.css"
import {
  capitalizeWords,
  spacesToCamelCase,
  toCamelCase,
} from "../../utils/unslugify"

// import slugify from "slugify"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ challenges }) {
  return (
    <>
      <Head>
        <title>React coding challenges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <index>
        <section className={styles.challengeCont}>
          {challenges.map((challenge) => {
            const string = `${challenge.title}`
            const capitalString = capitalizeWords(string)
            const link = spacesToCamelCase(capitalString)
            return (
              <article className={styles.challenge} key={challenge.id}>
                <a href={`http://localhost:3000/${link}`}>{challenge.title}</a>
              </article>
            )
          })}
        </section>
      </index>
    </>
  )
}

export async function getStaticSidePaths() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  const paths = data.map((challenge) => {
    return {
      params: { title: challenge.title },
    }
  })
  return {
    paths,
    fallback: true,
  }
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  return {
    props: {
      challenges: data,
    },
  }
}
