import Head from "next/head"
// import Image from "next/image"
import { Inter } from "next/font/google"
import styles from "../styles/HomePage.module.css"
import { capitalizeWords, spacesToCamelCase } from "../../utils/unslugify"

// import slugify from "slugify"

const inter = Inter({ subsets: ["latin"] })

export default function Home({ challenges }) {
  return (
    <>
      <Head>
        <title>React coding challenges</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <section className={styles.challengeCont}>
          {challenges.map((challenge) => {
            const string = `${challenge.title}`
            const capitalString = capitalizeWords(string)
            const link = spacesToCamelCase(capitalString)
            return (
              <a
                key={challenge.id}
                className={styles.linkText}
                href={`http://localhost:3000/${link}`}
              >
                <article className={styles.challenge}>
                  <h3 className={styles.linkText}>{challenge.title}</h3>
                </article>
              </a>
            )
          })}
        </section>
      </main>
    </>
  )
}

export async function getStaticSidePaths() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  const paths = data.map((challenge) => {
    return {
      params: { title: challenge.title },
    }
  })
  return {
    paths,
    fallback: true,
  }
}

export async function getStaticProps() {
  const response = await fetch("http://localhost:3000/api/challenges")
  const data = await response.json()
  return {
    props: {
      challenges: data,
    },
  }
}
